### ISSUE TITLE
error: /mnt/gentoo directory is not empty!

### ISSUE THREAD

**Issue by spikyatlinux** [owl4ce/gentoo-scripts#1]
Hey nice script, but perhaps you could add exeption for lost+found dir. I´ve add grep -v lost+found after the boot exeption like so `| grep -v 'boot' | grep -v lost+found`.

Regards

**Comment by owl4ce** [comment]
Oh, I forgot for `ext4`  partitition. Thanks for reminding!

**Comment by owl4ce** [comment]
Done in https://github.com/owl4ce/gentoo-scripts/commit/a010df22e1a36819026dbafbfc3c1fe1ecefd82e.
